FROM openjdk:17-jdk-slim AS build

# maven und git package installieren
RUN apt-get update && apt-get install -y maven git
# Set working directory 
WORKDIR /App
# Clone project
RUN git clone https://gitlab.com/bbwrl/m347-ref-card-01.git
# Set working directory 
WORKDIR /App/m347-ref-card-01
# Build the app
RUN mvn clean package -Dmaven.test.skip=true

# current dir is /App/m347-ref-card-01

# Start a new stage

FROM nielijun/alpine_latest
RUN apk add --no-cache openjdk17-jre

# Set working directory
WORKDIR /app
# Copy the built app from the build stage
COPY --from=build /App/m347-ref-card-01/target/*.jar /app/

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "app-refcard-01-0.0.1-SNAPSHOT.jar"]